-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 10:34:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database project_lunetic
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `project_lunetic` DEFAULT CHARACTER SET utf8 ;
USE `project_lunetic` ;

-- -----------------------------------------------------
-- Table `project_lunetic`.`opticians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`opticians` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`opticians` (
  `id_optician` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `company` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `other_address` VARCHAR(255) NULL,
  `postal_code` VARCHAR(50) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `mobile_phone` VARCHAR(50) NULL,
  `password` VARCHAR(255) NULL,
  `website` VARCHAR(255) NULL,
  `home_phone` VARCHAR(50) NULL,
  `finess_code` VARCHAR(20) NULL,
  `siret` VARCHAR(25) NULL,
  `vat_number` VARCHAR(45) NULL,
  `link_picture` VARCHAR(255) NULL,
  PRIMARY KEY (`id_optician`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`collections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`collections` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`collections` (
  `id_collection` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_collection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`models` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`models` (
  `id_model` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_collection` INT NOT NULL,
  PRIMARY KEY (`id_model`),
  CONSTRAINT `fk_models_collections`
    FOREIGN KEY (`id_collection`)
    REFERENCES `project_lunetic`.`collections` (`id_collection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`colors` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`colors` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`temples`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`temples` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`temples` (
  `id_temple` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_collection` INT NOT NULL,
  PRIMARY KEY (`id_temple`),
  CONSTRAINT `fk_temples_collections`
    FOREIGN KEY (`id_collection`)
    REFERENCES `project_lunetic`.`collections` (`id_collection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`wishlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`wishlists` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`wishlists` (
  `id_wishlist` INT NOT NULL AUTO_INCREMENT,
  `id_optician` INT NULL,
  `date` DATETIME NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_wishlist`),
  CONSTRAINT `fk_wishlists_opticians`
    FOREIGN KEY (`id_optician`)
    REFERENCES `project_lunetic`.`opticians` (`id_optician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`models_temples_colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`models_temples_colors` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`models_temples_colors` (
  `id_model_temple_color` INT NOT NULL AUTO_INCREMENT,
  `id_color_temple` INT NOT NULL,
  `id_model` INT NULL,
  `id_color_model` INT NOT NULL,
  `id_temple` INT NOT NULL,
  `id_wishlist` INT NOT NULL,
  PRIMARY KEY (`id_model_temple_color`),
  CONSTRAINT `fk_models_temples_colors_models`
    FOREIGN KEY (`id_model`)
    REFERENCES `project_lunetic`.`models` (`id_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_models_temples_colors_colors_temple`
    FOREIGN KEY (`id_color_temple`)
    REFERENCES `project_lunetic`.`colors` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_models_temples_colors_colors_model`
    FOREIGN KEY (`id_color_model`)
    REFERENCES `project_lunetic`.`colors` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_models_temples_colors_temples`
    FOREIGN KEY (`id_temple`)
    REFERENCES `project_lunetic`.`temples` (`id_temple`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_models_temples_colors_wishlists`
    FOREIGN KEY (`id_wishlist`)
    REFERENCES `project_lunetic`.`wishlists` (`id_wishlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`orders` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_optician` INT NOT NULL,
  `link_pdf` VARCHAR(255) NULL,
  `order_number` VARCHAR(100) NOT NULL,
  `date` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_order`),
  CONSTRAINT `fk_orders_opticians`
    FOREIGN KEY (`id_optician`)
    REFERENCES `project_lunetic`.`opticians` (`id_optician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`days` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`days` (
  `id_day` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`opening_hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`opening_hours` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`opening_hours` (
  `id_opening_hour` INT NOT NULL AUTO_INCREMENT,
  `start_morning` VARCHAR(45) NULL,
  `end_morning` VARCHAR(45) NULL,
  `start_afternoon` VARCHAR(45) NULL,
  `end_afternoon` VARCHAR(45) NULL,
  `id_optician` INT NOT NULL,
  `id_day` INT NULL,
  PRIMARY KEY (`id_opening_hour`),
  CONSTRAINT `fk_opening_hours_opticians`
    FOREIGN KEY (`id_optician`)
    REFERENCES `project_lunetic`.`opticians` (`id_optician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opening_hours_days`
    FOREIGN KEY (`id_day`)
    REFERENCES `project_lunetic`.`days` (`id_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_lunetic`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_lunetic`.`news` ;

CREATE TABLE IF NOT EXISTS `project_lunetic`.`news` (
  `id_news` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `subtitle` VARCHAR(255) NULL,
  `text` TEXT(1500) NULL,
  `link_picture` VARCHAR(255) NULL,
  PRIMARY KEY (`id_news`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
