import express from 'express';
import opticiansRouter from './opticians';
import authRouter from './auth';
import collectionsRouter from './collections';
import colorsRouter from './colors';
import templesRouter from './temples';
import newsRouter from './news';
import wishlistsRouter from './wishlists';
import openingHoursRouter from './openingHours';
import ordersRouter from './orders';
import modelsRouter from './models';
import daysRouter from './days';
import contactGuestRouter from './contactGuest';
import contactProRouter from './contactPro';
import contactConfirmationRouter from './contactConfirmation';
import modelsTemplesColorsRouter from './modelsTemplesColors';
import carouselsRouter from './carousels';
import conceptImagesRouter from './conceptImages';
import usImagesRouter from './usImages';
import modelsImagesRouter from './modelsImages';

const setupRoutes = (app: express.Application) => {
  app.use('/api/opticians', opticiansRouter);
  app.use('/api/login', authRouter);
  app.use('/api/collections', collectionsRouter);
  app.use('/api/colors', colorsRouter);
  app.use('/api/temples', templesRouter);
  app.use('/api/news', newsRouter);
  app.use('/api/wishlists', wishlistsRouter);
  app.use('/api/openingHours', openingHoursRouter);
  app.use('/api/orders', ordersRouter);
  app.use('/api/models', modelsRouter);
  app.use('/api/days', daysRouter);
  app.use('/api/contact-guest', contactGuestRouter);
  app.use('/api/contact-pro', contactProRouter);
  app.use('/api/contact-confirmation', contactConfirmationRouter);
  app.use('/api/glasses', modelsTemplesColorsRouter);
  app.use('/api/carousels', carouselsRouter);
  app.use('/api/concept-images', conceptImagesRouter);
  app.use('/api/us-images', usImagesRouter);
  app.use('/api/models-images', modelsImagesRouter);
};

export default setupRoutes;
